settings:
  title: 'Slang Status Page'
  url: 'https://status.slangapp.com/' # used for Slack messages
  logo: logo-128x128.png # image in ./public/ folder
  daysInHistogram: 30 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: slangapp-com
    name: slangapp.com
    description: 'The Slang marketing site'
    url: 'https://slangapp.com/'
    method: GET
    expectStatus: 200
    followRedirect: true

  - id: api-slangapp-com # unique identifier
    name: api.slangapp.com
    description: 'The Slang application API' # default=empty
    url: 'https://api.slangapp.com/health/200' # URL to fetch
    method: GET # default=GET

  - id: learn-slangapp-com
    name: learn.slangapp.com
    description: 'The Slang learn application'
    url: 'https://learn.slangapp.com/'
    method: GET
    expectStatus: 200
    followRedirect: true

  - id: admin-slangapp-com
    name: admin.slangapp.com
    description: 'The Slang admin application'
    url: 'https://admin.slangapp.com/'
    method: GET
    expectStatus: 200
    followRedirect: true
